version: '3.8'

services:
  loadbalancer:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - HEALTH_CHECK_INTERVAL=10s
      - STRATEGY=round-robin
      - BACKEND_URLS=http://backend1:8081,http://backend2:8082
    depends_on:
      - backend1
      - backend2
    volumes:
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

  backend1:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - ..:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: go run ./backend/main.go -port 8081
    expose:
      - "8081"

  backend2:
    image: golang:1.21-alpine
    working_dir: /app
    volumes:
      - ..:/app
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build
    command: go run ./backend/main.go -port 8082
    expose:
      - "8082"

volumes:
  go-mod-cache:
  go-build-cache: 